apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: crony
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/bash
            - uname
          activeDeadlineSeconds: 10
          restartPolicy: OnFailure

