apiVersion: v1
kind: Pod
metadata:
  name: redis-ns
  namespace: web
spec:
  containers:
  - image: redis
    name: redis
    ports:
    - containerPort: 9090
      name: http
      protocol: TCP
      protocol: UDP
